jobfile = "job.create_segment_{}.madx"
measurement_madx = "measurement_{}.madx"
corrections_madx = "corrections_{}.madx"
twiss_forward = "twiss_{}_forward.dat"
twiss_backward = "twiss_{}_backward.dat"
twiss_forward_corrected = "twiss_{}_forward_corrected.dat"
twiss_backward_corrected = "twiss_{}_forward_corrected.dat"

FORWARD = "FWDPROP"
BACKWARD = "BCKPROP"
CORRECTED = "COR"
