MACROS_DIR = "macros"
OBS_POINTS = "observation_points.def"
MODIFIERS_MADX = "modifiers.madx"
TWISS_BEST_KNOWLEDGE_DAT = "twiss_best_knowledge.dat"
TWISS_ELEMENTS_BEST_KNOWLEDGE_DAT = "twiss_elements_best_knowledge.dat"
TWISS_ADT_DAT = "twiss_adt.dat"
TWISS_AC_DAT = "twiss_ac.dat"
TWISS_ELEMENTS_DAT = "twiss_elements.dat"
TWISS_DAT = "twiss.dat"
ERROR_DEFFS_TXT = "error_deffs.txt"
JOB_ITERATE_MADX = "job.iterate.madx"

GENERAL_MACROS = "general.macros.madx"
LHC_MACROS = "lhc.macros.madx"

B2_SETTINGS_MADX = "b2_settings.madx"
B2_ERRORS_TFS = "b2_errors.tfs"