# Runs all tests 
name: All Tests

defaults:
  run:
    shell: bash

on:  # Runs on any push event to any branch except master (the coverage workflow takes care of that)
  push:
    branches-ignore:
      - 'master'

env:
  UV_SYSTEM_PYTHON: 1  # so that uv pip installs in the system python installed by actions/setup-python

jobs:
  uv-example: 
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: [3.9, "3.10", 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml
          cache-suffix: py${{ matrix.python-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project package
        run: uv pip install '.[test]' -v
