PI = 3.14159265358979323846
TWOPI = PI * 2.0
kEPSILON = 1.0e-12
AMP_BETA_NAME = "beta_amplitude_"
BETA_NAME = "beta_phase_"
PHASE_NAME = "phase_"
TOTAL_PHASE_NAME = "total_phase_"
DISPERSION_NAME = "dispersion_"
NORM_DISP_NAME = "normalised_dispersion_"
ORBIT_NAME = "orbit_"
KICK_NAME = "kick_"
EXT = ".tfs"
IP_NAME = "interaction_point_"
ERR = "ERR"
DELTA = "DELTA"
MDL = "MDL"
PLANES = ("X", "Y")
RES = "RES"
